### ISSUE TITLE
Omit JSON.stringify()

### ISSUE THREAD

**Issue by dpnishant** [dpnishant/appmon#1]
<@oleavr> dpnishant: Btw, you can omit JSON.stringify() when you send() data, because send() will JSON.stringify() the data for you, and the language binding, e.g. frida-node, will do the reverse (JSON.parse()) so you get an object / dict / etc. native to the language binding

**Comment by subho007** [comment]
This is nice ! @dpnishant you should reomve the JSON.stringify then ?

**Comment by dpnishant** [comment]
Will do later
