### ISSUE TITLE
add yololib option to ipa_installer

### ISSUE THREAD

**Issue by dpnishant** [dpnishant/appmon#10]
https://github.com/KJCracks/yololib

**Comment by gameFace22** [comment]
Hey,
From [https://github.com/dpnishant/appmon/blob/master/ipa_installer/ipa_installer.py](here), I can see appmon uses optool to inject dylib. This should be replaced by yololib? Or something else? Please let me know.

**Comment by dpnishant** [comment]
As of now, optool works fine for me and others I know. This ticket was created to have more options in the tool and try a different method, incase one of them breaks. But since optool is meeting our requirements as of now. We are good and this task is at lower priority.

**Comment by dpnishant** [comment]
Doesn't seem to be necessary anymore
