### ISSUE TITLE
[ERROR]: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by salman0ansari** [dpnishant/appmon#126]
command used:
`python3 apk_builder.py --apk /home/apex/Desktop/Frida/app.apk`

error:
```
[I] Preparing work directory...
[I] Expanding APK...
Traceback (most recent call last):
  File "/home/apex/Desktop/Frida/appmon/apk_builder/apk_builder.py", line 96, in <module>
    package_name = apk_dump.split("package: name=")[1].split(" ")[0].strip("'\"\n\t ")
TypeError: a bytes-like object is required, not 'str'
```
specs:
![image](https://user-images.githubusercontent.com/30106022/183399116-eecba0d3-1415-4781-b4fb-072e29d96d13.png)

**Comment by gam04** [comment]
Same here.

It seems its due by `aapt` output.

the `apk_builder.py` depends on specific `aapt` version?

**Comment by gam04** [comment]
Hi @salman0ansari , for now you can bypass this issue by converting `subprocess` byte output into `str`:

example:
```python
# use bytes.decode('utf-8')
apk_dump = subprocess.check_output(["aapt", "dump", "badging", apk_path]).decode('utf-8')
```
