### ISSUE TITLE
Why intercepting android.content.ContextWrapper class

### ISSUE THREAD

**Issue by kochia3** [dpnishant/appmon#127]
Why Android scripts intercept `android.content.ContextWrapper` class for different things?
Is this class somehow lower level for other classes?

**Comment by dpnishant** [comment]
@kochia3 t's done because `android.content.Context` is an abstract class that cannot be used to create objects but `android.content.ContextWrapper` extends `android.content.Context` and exports the methods we want to hook.

Closing it as not an issue.
