### ISSUE TITLE
Error: Java API not available

### ISSUE THREAD

**Issue by xly1208** [dpnishant/appmon#15]
I got this error below.

[INFO] Attached to com.tencent.mobileqq
[INFO] Building injection...
[INFO] Instrumentation started...
Error: Java API not available
    at assertJavaApiIsAvailable (gumjs-java.js:128:23)
    at Runtime.perform (gumjs-java.js:246:13)
    at script1.js:46:6
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

What is the problem?

**Comment by dpnishant** [comment]
Hey @xly1208,

Can you please provide some more debug info, what are your trying on do using which os on what mobile os using what command?

--
dpnishant

**Comment by dpnishant** [comment]
Since there has been no response to this issue. I will close it and may be reopened later.
