### ISSUE TITLE
No apps available to select

### ISSUE THREAD

**Issue by javixeneize** [dpnishant/appmon#17]
Hi

I am starting the app python appmon.py -p "android" -a "packagename" -s "scripts/Android/" -o "test/" (note i have removed the app name for packagename)

I can correctly see the dump in the terminal

[Dec 02 2016  4:57 PM] Dumped to test/packagename.db

I can correctly see the db file downloaded and i can open it, but going to localhost:5000, when i click in select app button, there is no app there to choose

If i go to next screen without selecting the app, it fails as the tables are empty

Any idea what could be the problem?

Thanks

**Comment by max01203** [comment]
Hi, 
Could you check which version that you used? You have to run it using python2.
Did you check using the command like this : 
`python appmon.py -p android -s scripts/Android/ -a packagename`
From my side, I have to run the previous command and then run the application packagename manually, and then it will appear on the list, if not try to refresh several times. I've checked with the last version and it is working with like 4 differents application.

Thanks,

**Comment by dpnishant** [comment]
Thanks @max01203
