### ISSUE TITLE
App under the 64 - bit system can not use this tool? 

### ISSUE THREAD

**Issue by z6101681** [dpnishant/appmon#18]
python appmon.py -p android -s scripts/Android -a com.xx.account

[ERROR] unable to handle 64-bit processes due to build configuration
Traceback (most recent call last):
  File "appmon.py", line 264, in init_session
    session = device.attach(app_name)
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 96, in attach
    return Session(self._impl.attach(self._pid_of(target)))
NotSupportedError: unable to handle 64-bit processes due to build configuration
^CTraceback (most recent call last):
  File "appmon.py", line 305, in <module>
    script.unload()
NameError: name 'script' is not defined

**Comment by max01203** [comment]
Hello,
For which system do you speak about? Your desktop or arm64?
If it's for arm64 you have to take the proper version of frida-server  [here](https://github.com/frida/frida/releases)

**Comment by dpnishant** [comment]
Thanks @max01203
