### ISSUE TITLE
seems do not support the latest frida since V8 to Duktape

### ISSUE THREAD

**Issue by DARKTEMPLE9** [dpnishant/appmon#20]
Any idea to fix this bug？ It seems frida convert V8 to Duktape.
Like this:https://github.com/frida/frida/issues/210

[INFO] Attached to com.netease.mail
[INFO] Building injection...
[INFO] Instrumentation started...
TypeError: not configurable
    at ensureClass (frida/node_modules/frida-java/lib/class-factory.js:290)
    at ensureClass (frida/node_modules/frida-java/lib/class-factory.js:268)
    at frida/node_modules/frida-java/lib/class-factory.js:115
    at frida/node_modules/frida-java/index.js:193
    at frida/node_modules/frida-java/lib/vm.js:35
    at java.js:1231
    at script1.js:64

**Comment by max01203** [comment]
Hi, 
It is weird because I've checked on android and it is working using frida-server-9.1.7 I'm not sure if by saying V8 you speak about the last frida version that is at this time the 9.1.8 (that I haven't check it is working with appmon). I assume that you're using nodejs and not python?

Thanks,

**Comment by DARKTEMPLE9** [comment]
I change frida 9.0.0 to frida 9.1.7 and solve this problem. Thanks!
