### ISSUE TITLE
"get_usb_device" often times out

### ISSUE THREAD

**Issue by ohayman** [dpnishant/appmon#26]
I'd recommend passing a "maximum time to wait" value to get_usb_device, as I often encounter a timeout when running Frida code, including this. 1-2 seconds should do the job. I'm not sure whether this is due to the delays associated with accessing Virtual Machine "hardware", however.

**Comment by dpnishant** [comment]
Thanks @ohayman  for reporting this. I have fixed this in 82e793cc219dbbb5cb20a2c94c480b813f7b151f
