### ISSUE TITLE
payload['overloads'] not populated in android_tracer.py, leading to exception.

### ISSUE THREAD

**Issue by ohayman** [dpnishant/appmon#27]
The 'overloads' entry in the payload dictionary is not getting populated, this leads to a lot of (handled) exceptions, however also leads to the program saying "didn't find anything. Quitting". After patching this, I received several hundred results.

The following code is a temporary workaround:

if not 'overloads' in payload:
    payload['overloads'] = ''

**Comment by dpnishant** [comment]
Hey @ohayman Can you please provide more information on this? The file and the line number?

**Comment by ohayman** [comment]
Sorry - to be more specific, the error occurs in the on_message function of android_tracer.py. When appending to the classCandidates list on line 64, payload['overloads'] has not been created.

**Comment by dpnishant** [comment]
@ohayman Fixed in https://github.com/dpnishant/appmon/commit/bf3cee9e3676ecb1f446c25aa7f6573a85794ace. Also this commit brings a new feature that accepts wildcard names for methods. 😊 

Closing this issue for now. Reopen if the issue persists.
