### ISSUE TITLE
sleep(5) statements in appmon.py causes "session detatched" error

### ISSUE THREAD

**Issue by ohayman** [dpnishant/appmon#28]
Where the code checks if you want to spawn the process, the sleep statements break the code - would suggest removing them, similar to android_intruder.py

**Comment by dpnishant** [comment]
Hi @ohayman Does it work for you by removing the sleep statements? Which device and Android version are you using?

**Comment by ohayman** [comment]
Yes, it works when I remove the sleep statements. The device I am using is a Motorola G4.

**Comment by dpnishant** [comment]
Fixed in https://github.com/dpnishant/appmon/commit/427c0fcb085810459dd036a607141f03a202775a
