### ISSUE TITLE
Launching appmon tells SyntaxError

### ISSUE THREAD

**Issue by Raphkitue** [dpnishant/appmon#29]
Hello, when I try to launch any of the appmon tools I get this error, and when i put parentheses for the print it just pops other syntax errors.
I'm running python 3.6.1.

```
File "appmon.py", line 33
    """
      ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by dpnishant** [comment]
@Raphkitue This project is built using Python 2.7. Hence the error.
