### ISSUE TITLE
Instrumentation started but can not hook anything.

### ISSUE THREAD

**Issue by z6101681** [dpnishant/appmon#30]
can not hook anything in android 6.0
frida  10.0.5
[INFO] Attached to com.sankuai.meituan.takeoutnew
[INFO] Building injection...
[INFO] Instrumentation started...
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

It's running but nothing happen.

![image](https://cloud.githubusercontent.com/assets/15312660/26087572/1c0d4d42-3a24-11e7-93e2-3cd494f0dc65.png)

**Comment by z6101681** [comment]
![image](https://cloud.githubusercontent.com/assets/15312660/26090102/4f9db7d0-3a35-11e7-90bf-1ad5c06b71c5.png)

**Comment by dpnishant** [comment]
Hey @z6101681 

After the instrumentation has started, you need to use/interact with the app to start capturing the API calls, if it has not already started?

--
Nishant

**Comment by z6101681** [comment]
I'm  pretty sure I have been interact with the app,but still nothing happen.

**Comment by z6101681** [comment]
I'm not using the virtual,Does it affect the appmon hook?

**Comment by dpnishant** [comment]
Hey @z6101681, No it doesn't depend on the device type. It should work on both hardware as well as simulator/virtual devices. Does it happen with all the apps or just for some specific app?

**Comment by z6101681** [comment]
I have been try three difference app at mine phone.
firmware:http://firmware.meizu.com/Firmware/Flyme/PRO_6/6.7.4.25/cn_beta/20170420000800/5cc1becc/update.zip

I use my own  frida scripts is working,I don't know why appmon did not working...

**Comment by onemanarmy8** [comment]
I hawe same problem on Windows.

**Comment by dpnishant** [comment]
Needs more info to reproduce the issue. Please reopen once more information is available.
