### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by AkshayJainG** [dpnishant/appmon#4]
For android , when is it coming?

**Comment by dpnishant** [comment]
@AkshayJainG Android support is due sometime down the line. Actually I'm waiting for the Frida to add support for ART, as I didn't wanted to start with the dying Dalvik. Hence no ETA as of now. But if ART support is going to take too long I might want to start looking at Dalvik again. :)

**Comment by dpnishant** [comment]
Android Support added! Enjoy! 👍
