### ISSUE TITLE
Apps Crashing when made with Apk Builder

### ISSUE THREAD

**Issue by bilaljawed** [dpnishant/appmon#41]
Hello,

This is my first time trying AppMon. I have tried a few apps made using apk builder but each of them crashes on load, its not like there is a security mechanism built on it because i have even tried on my own apps, also i even tried the KitKat version of android till android 6, none of it works. is anyone else having this issue?

**Comment by dpnishant** [comment]
Can you please send me a sample APK (if its not private) that is failing for you?

**Comment by ducphanduyagentp** [comment]
Shouldn't the APK be signed before zipalign? apkbuilder zipaligns the APK before signing it, making the zipalign verification failed on the final APK.

**Comment by dpnishant** [comment]
@ducphanduyagentp Can you verify if your APK installs and runs fine if it is signed before `zipalign`? 

To do that just cut & paste [this code block](https://github.com/dpnishant/appmon/blob/master/apk_builder/apk_builder.py#L194-L205) before [this line](https://github.com/dpnishant/appmon/blob/master/apk_builder/apk_builder.py#L183).

**Comment by dpnishant** [comment]
This issue should have been fixed with commit id https://github.com/dpnishant/appmon/commit/da41b849bc703d34cd4f331c915766086d762954. Please reopen this issue if the problem still persists.
