### ISSUE TITLE
Cannot select App

### ISSUE THREAD

**Issue by schniggie** [dpnishant/appmon#5]
Hey I'm, using latest version from github.

After I start appmon the instrumentation looks ok:

```
python appmon.py -p ios -a Auto
[INFO] Attached to Auto
[INFO] Building injection...
[INFO] Instrumentation started...
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
[INFO] Attached to Auto
[INFO] Building injection...
[INFO] Instrumentation started...
127.0.0.1 - - [20/Jul/2016 11:28:04] "GET / HTTP/1.1" 200 -
```

But inside the web interface I cannot select the app, the selection is empty.

Any hints? I also tried another app but same result.

**Comment by sanjogpandasp** [comment]
You need to start appmon with the scripts as one of the parameter ie,

$ python appmon.py -p "ios" -s "scripts/" -a 'appname'

**Comment by schniggie** [comment]
thanks ;) can be closed.

**Comment by dpnishant** [comment]
Thanks @sanjogpandasp 👍
