### ISSUE TITLE
apk_builder.py fails with unzip:  cannot find or open lib.zip, lib.zip.zip or lib.zip.ZIP

### ISSUE THREAD

**Issue by rena2019** [dpnishant/appmon#50]
I executed the following command line

$ python apk_builder.py --apk myapp.apk

but it fails with the following error message

[I] Preparing work directory...
[I] Expanding APK...
[I] Searching .smali
[I] Patching .smali
[I] Injecting libs
unzip:  cannot find or open lib.zip, lib.zip.zip or lib.zip.ZIP.
Traceback (most recent call last):
  File "apk_builder.py", line 168, in <module>
    unzip_output = subprocess.check_output(["unzip", LIB_FILE_PATH, "-d", lib_dir])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['unzip', 'lib.zip', '-d', '/tmp/appmon_apk/myapp/lib']' returned non-zero exit status 9

What's wrong?

**Comment by dpnishant** [comment]
@rena2019 You need to first execute the script (provided with apk_builder.py)

"sh getlibs.sh" (without quotes)
