### ISSUE TITLE
Import database as db error

### ISSUE THREAD

**Issue by R3zk0n** [dpnishant/appmon#64]
Hi all, Ive noticed that when running appmon, it will give you error stating that there was a issue on __init__.py line 67 

Referring to that i see the code below 

```

<<<<<<< HEAD
        try:
            artifact_value = artifact_value.replace("<", "&lt;").replace(">", "&gt;")
        except AttributeError as e:
            pass
=======
        artifact_value = artifact_value.replace("<", "&lt;").replace(">", "&gt;")
>>>>>>> 2eb209ce1d4b4d34b0c9dab94ca63c44079fbdae
      else

```
Removable of the Head and == and >> 2eb will allow the application to run normally. 👍

**Comment by dpnishant** [comment]
This issue is fixed in PR #66
