### ISSUE TITLE
issues with android-sdk command-line tools

### ISSUE THREAD

**Issue by alonf1983** [dpnishant/appmon#67]
Hi
Per the 5.b we should install the android-sdk command-line tools and execute the ./andorid command.
this command is not available any more as you can see:

root@ubuntu:~/Downloads/tools# ./android
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command ""

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk

---

could you help with workaround? 

Thanks

**Comment by dpnishant** [comment]
How is this issue related to this project? Please reopen once you have more details related to appmon project. Thanks
