### ISSUE TITLE
Webview postdata from Object to string (Question)

### ISSUE THREAD

**Issue by Radzhab** [dpnishant/appmon#68]
I want detect which params sended to Webview. In logger i see this data

![image](https://user-images.githubusercontent.com/2556411/35806260-edb85134-0a8f-11e8-8b06-9b1cc2541828.png)
How convert it from Object to string readable  data?

**Comment by dpnishant** [comment]
Thanks @Radzhab for the bug report. I have tried to fix the bug in https://github.com/dpnishant/appmon/commit/6ca5db9cbaf88fd84bcb9a22dd6e21d37a75a6a3. Please do `git pull origin master` and re-test. It should hopefully work.

**Comment by Radzhab** [comment]
thx!

**Comment by Radzhab** [comment]
pls add same operation for other scripts. Example,

javax.crypto.Cipher
--

**Comment by dpnishant** [comment]
Thanks @Radzhab  for the bug report. I have tried to fix the bug in https://github.com/dpnishant/appmon/commit/524fcd3135431c1b7fad78964129e07a1f450b53. Please do git pull origin master and re-test. It should hopefully work.

**Comment by dpnishant** [comment]
Closing this issue as no further work is planned.
