### ISSUE TITLE
Blank param "appname"

### ISSUE THREAD

**Issue by ahvahsky2008** [dpnishant/appmon#70]
I want analyze this app https://play.google.com/store/apps/details?id=app.source.getcontact
When i started appmon, in logs all correct, but in browser i dont see app name

![image](https://user-images.githubusercontent.com/8035828/36812246-96280626-1ce1-11e8-8d7c-d0b787942dd5.png)
![image](https://user-images.githubusercontent.com/8035828/36812263-b0e083a8-1ce1-11e8-914c-daf869b82add.png)

**Comment by ChD1** [comment]
You forgot the -s option. Try add: -s scripts/Android

**Comment by dpnishant** [comment]
@ahvahsky2008 Please reopen the issue, if the problem still persists after following @ChD1's instructions.
