### ISSUE TITLE
NameError: global name 'raw' is not defined`

### ISSUE THREAD

**Issue by andrewBatutin** [dpnishant/appmon#81]
I have an error when i try to run

`python ipa_installer.py -ipa <path>`

i use python 2.7

`No "iPhone Developer" identity found!
Traceback (most recent call last):
  File "ipa_installer.py", line 132, in <module>
    dev_identity = getDeveloperId()
  File "ipa_installer.py", line 61, in getDeveloperId
    devID = raw("Enter \"iPhone Developer\" Identity Hash: ")
NameError: global name 'raw' is not defined`

AppMon IPA Installer v0.1, Copyright 2016 Nishant Das Patnaik

what is that raw function? 
have i missed some dependency?

**Comment by dpnishant** [comment]
Seems like you dont have a iPhone Developer profile on your system. If you're using macOS, you can Google the steps to create one.

**Comment by andrewBatutin** [comment]
this is rather strange, case i have one
my fix was specify devID directly in a  script as a string value 

it worked

**Comment by andrewBatutin** [comment]
do you know what package **raw** function belongs to?

**Comment by dpnishant** [comment]
can you pull the changes and try again?
