### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by blshkv** [dpnishant/appmon#86]
Frida has moved to the python-prompt-toolkit 2.x recently:
https://github.com/frida/frida-tools/commit/9f5f4c3666af6dd493a4b00b09e34876d7d36851

ipython>=7 depends on  python-prompt-toolkit 2.x , however they dropped python2 support.
That makes the whole thing complicated.

Could you consider upgrading the code to python3 please?

**Comment by dpnishant** [comment]
That shouldn't be too much of change. Would you have time for a Pull Request?

**Comment by AbhilashG97** [comment]
@dpnishant can I send a pull request for this issue if no one is working on it?

**Comment by dpnishant** [comment]
@AbhilashG97 Absolutely! Thank you.

**Comment by blshkv** [comment]
ping

**Comment by blshkv** [comment]
ping

**Comment by blshkv** [comment]
PING

**Comment by blshkv** [comment]
d80fbdd375d0ba2762de7473737f433539a0eeff
