### ISSUE TITLE
No such file or directory while signing APK

### ISSUE THREAD

**Issue by SamsadSajid** [dpnishant/appmon#87]
> Python version: 2.7 (Venv)
Traceback: 

> [I] Aligning APK
> [I] APK alignment verified
> [I] Signing APK
> Traceback (most recent call last):
>   File "apk_builder.py", line 197, in <module>
>     sign_status = subprocess.check_output(["apksigner", "sign", "--verbose", "--ks", "appmon.keystore", "--ks-pass", "pass:appmon", "--out", signed_apk_path, aligned_apk_path])
>   File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

I've followed [this](https://github.com/dpnishant/appmon/wiki/5.b-Setup-on-Android-%5BNon-Rooted%5D) and installed everything menstioned here.

**Comment by dpnishant** [comment]
Path of `apksigner` is not added to the `$PATH` environment variable.  Follow the steps properly to fix it.

**Comment by SamsadSajid** [comment]
There's no mention of `apksigner` in the mentioned [link](https://github.com/dpnishant/appmon/wiki/5.b-Setup-on-Android-%5BNon-Rooted%5D) for Setup on Android[Non Rooted]
