### ISSUE TITLE
sniffing

### ISSUE THREAD

**Issue by lintangtimur** [dpnishant/appmon#88]
is appmon can perform sniffing traffic?
before i know about appmon, i use frida-server-android + objection + burp that can sniff from android emulator device from android studio. Is appmon capable do that?

**Comment by dpnishant** [comment]
Yes. Appmon has hooks for HTTP traffic. But if you see something not working as expected. Please file a bug.

**Comment by lintangtimur** [comment]
is appmon sniff https traffic? and bypass cert pinning?

**Comment by dpnishant** [comment]
Yes. Since appmon hooks the network apis, you should be able to see it before encryption and it has cert pinning bypass for iOS.

**Comment by lintangtimur** [comment]
and for non rooted android devices?

**Comment by dpnishant** [comment]
https://www.chromestatus.com/feature/5903385005916160 is a signal that Public Key Pinning might be obsolete in the near future. Hence there was no effort made to include support for Android. But if its really needed, then it should not take much time to implement for someone who has experience with Android development and Frida experience.
