### ISSUE TITLE
NO prompt "Frida: Listening on TCP port 27042"

### ISSUE THREAD

**Issue by KevinIsSun** [dpnishant/appmon#9]
I try to install an ipa by using ipa_installer.py  on a non jailbroken device. But there was no prompt "Frida: Listening on TCP port 27042" at the end of installing, just a single "success" and the ipa was successful installed. Surely when i use frida-ps -U it appears "unable to connect to remote frida-server". 
       And I try to read the system log, nothing useful was found. So how can I fix this question? THX for ur help.

**Comment by dpnishant** [comment]
Hi @KevinIsSun,

The `Frida: Listening on TCP port 27042` prompt can take upto 2-3 minutes (on my iPad Mini 4) to appear depending upon the CPU/Memory load. 

How long did you wait?

**Comment by KevinIsSun** [comment]
@dpnishant  thank u for the reply. I wait enough time on my iPhone 6.And the application I injected dylib had finished it's launch. just a "success". I think the main question is I don't have any idea about how to debug it.Any advices? Thanks for ur help.

**Comment by dpnishant** [comment]
Hey Kevin,

Let me know what do you see when you run the command `security
find-identity -v -p codesigning`.

Do you see a hash for an "iPhone Developer" profile?

**Comment by KevinIsSun** [comment]
I have a few profile appears in my console, just like some "iPhone Developer: xxxx@icloud.com (XXXXXXXXX)" I have done some work about use frida in jailbroken device or use XCode in non-jailbroken device and all of them was success. And I just follow ur document except add the embedded.mobileprovision by manual. And I was sure it was a right provision file because if it was not, the application would not run normally.

**Comment by KevinIsSun** [comment]
![image](https://cloud.githubusercontent.com/assets/5045205/17361590/dcce2b62-59a3-11e6-8ba8-c6d2513c3126.png)

here is the syslog. Maybe useful

**Comment by dpnishant** [comment]
@KevinIsSun Did you have any success on this? Is it possible to share the IPA with me to debug at my end?

**Comment by KevinIsSun** [comment]
@dpnishant I send a email with the ipa to u, and thanks for your help

**Comment by KevinIsSun** [comment]
@dpnishant  I think i found the problem. The injection was failed.So no dylib was load.I never use optool.Maybe there were some bugs. I use yololib and the dylib was load successful.

**Comment by dpnishant** [comment]
@KevinIsSun thanks for the confirmation. I shall then add yololib option to the tool aslong with optool.

**Comment by KevinIsSun** [comment]
Thanks ur help too! But I met another problem. I will try to fix it. If not, i will open another issue ：）
